apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: techstylersacr.azurecr.io/mbaoma/tech-stylers-image:latest
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_URL
            - name: MONGODB_URI_LOCAL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGODB_URI_LOCAL
          resources:
            limits:
              memory: "256Mi" 
              cpu: "200m"
            requests:
              memory: "128Mi"
              cpu: "100m"

      volumes:
        - name: cache-storage
          persistentVolumeClaim:
            claimName: app-pvc
      imagePullSecrets:
        - name: my-acr-secret