apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: techstylersacr.azurecr.io/mbaoma/tech-stylers:latest
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_URL
            - name: MONGODB_URI_LOCAL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGODB_URI_LOCAL
          resources:
            limits:
              memory: "500Mi" 
              cpu: "500m"
            requests:
              memory: "300Mi"
              cpu: "250m"

      volumes:
        - name: cache-volume
          emptyDir: {}