apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: cache
          image: redis:alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: cache-storage
              mountPath: /data
          resources:
                  limits:
                    memory: "500Mi" 
                    cpu: "500m"
                  requests:
                    memory: "300Mi"
                    cpu: "250m"

      volumes:
        - name: cache-storage
          persistentVolumeClaim:
            claimName: app-pvc